## This set of functions allows the inverse of a matrix
## to be found quickly by caching the inverse. The inverse
## is only calculated if it has not already been calculated,
## thus eliminating repetitive calculations of the inverse
## of the same matrix.

## This function returns a list of four functions given a
## argument that is a matrix. These functions include get
## and set to get and set the matrix itself. They also include
## getInverse to obtain the inverse of the matrix and setInverse
## to cache the inverse of the matrix.
##
## @param x a matrix
## @return a list of functions get, set, getInverse, setInverse

makeCacheMatrix <- function(x = matrix()) {
	inverse <- NULL

	## set the data x to the new data y and clear the stored
	## inverse since it has not been calculated yet for the new data.
	##
	## @param y the new matrix to be stored
	set <- function(y) {
		x <<- y
		inverse <<- NULL
	}
	
	## return the matrix x
	##
	## @return x the matrix x
	get <- function() x
	
	## set the stored inverse to the calculated inverse.
	##
	## @param newInverse the calculated inverse of the matrix x
	setInverse <- function(newInverse) inverse <<- newInverse
	
	## return the stored inverse of the matrix x
	##
	## @return inverse the stored inverse
	getInverse <- function() inverse
	
	## generate the list containing the functions
	## get, set, getInverse, and setInverse.
	## This list is returned.
	list(set = set, get = get, getInverse = getInverse, setInverse = setInverse)


}


## This function returns the inverse of a matrix. It takes an
## argument of type list as generated by the function makeCacheMatrix.
## If the inverse of the matrix has not been calculated, the inverse
## is calculated and cached. Otherwise the cached inverse is returned.
## This enables the inverse of a matrix to be found quickly and eliminates
## multiple calculations of the inverse of the same matrix.
##
## @param list(get, set, getInverse, setInverse)
## @return inverse the inverse of the matrix in the list

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'

	## Get the stored inverse of the matrix
	inverse <- x$getInverse()

	## Calculate the inverse if it has not been calculated yet
	if (is.null(inverse)) {
		message("Calculating inverse")

		## Get the data
		matrixX <- x$get()

		## Calculate the inverse
		inverse <- solve(matrixX)

		## Cache the inverse
		x$setInverse(inverse)
	}
	## return the inverse
	inverse
}
